// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32Sonos

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_VolumeBar = NULL;lv_obj_t *ui_VolumeLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_VolumeBar = lv_bar_create(ui_Screen1);
lv_obj_set_width( ui_VolumeBar, lv_pct(89));
lv_obj_set_height( ui_VolumeBar, lv_pct(62));
lv_obj_set_align( ui_VolumeBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_VolumeBar, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_VolumeBar, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_VolumeBar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VolumeBar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VolumeBar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VolumeBar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_VolumeBar, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VolumeLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_VolumeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VolumeLabel, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_VolumeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_VolumeLabel,"");
lv_obj_set_style_text_font(ui_VolumeLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_VolumeBar= NULL;
ui_VolumeLabel= NULL;

}
